# Generated by Django 5.0.4 on 2024-05-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_banned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('is_active', 'pk'), 'permissions': [('can_edit_is_banned', 'Can edit is_banned'), ('can_view_all_users', 'Can view all users')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
