# Generated by Django 5.0.4 on 2024-05-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='тема поста')),
                ('body', models.TextField(verbose_name='тело поста')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='превью')),
                ('view_count', models.IntegerField(default=0, verbose_name='просмотры')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='дата публикации поста')),
            ],
            options={
                'verbose_name': 'Пост блога',
                'verbose_name_plural': 'Посты блога',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='электронная почта')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='отчество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='частота отправки')),
                ('days_until_next_mailing', models.IntegerField(verbose_name='количество дней до следующей отправки')),
            ],
            options={
                'verbose_name': 'Частота рассылки',
                'verbose_name_plural': 'Частоты рассылки',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='дата первой отправки')),
                ('status', models.CharField(choices=[('Новая', 'Новая'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Новая', verbose_name='статус рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(auto_now=True, verbose_name='дата последней попытки')),
                ('is_success', models.BooleanField(blank=True, null=True, verbose_name='успешность последней попытки')),
                ('server_answer', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
