# Generated by Django 5.0.4 on 2024-05-27 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.AddField(
            model_name='client',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='client_list',
            field=models.ManyToManyField(to='service.client', verbose_name='список клиентов'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='service.frequency', verbose_name='частота отправки рассылки'),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='service.client', verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='service.mailing', verbose_name='рассылка'),
        ),
        migrations.AddField(
            model_name='message',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='message_to_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='service.message', verbose_name='сообщение для отправки'),
        ),
    ]
