# Generated by Django 5.0.4 on 2024-05-31 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': [('can_view_blog_posts', 'Can view all posts')], 'verbose_name': 'Пост блога', 'verbose_name_plural': 'Посты блога'},
        ),
    ]
